### ISSUE TITLE
ENS Is Implemented On Portfolio.Emoon.io

### ISSUE THREAD

**Issue by pointtoken** [pointtoken/Contracts#3]
@decanus @Arachnid 

Please see the implementation of ENS at [https://portfolio.emoon.io/whois](https://portfolio.emoon.io/whois) and [https://portfolio.emoon.io/portfolios/default/queryblockchain](https://portfolio.emoon.io/portfolios/default/queryblockchain)
What do I do for GitCoin bounty?

**Comment by decanus** [comment]
@pointtoken this bounty is only for projects who have not yet integrated ENS, sorry about that.

**Comment by Arachnid** [comment]
Thanks for integrating ENS! As @decanus says, the intention of the bounty is to offer an incentive for outside contributors to implement ENS on projects where the team doesn't have time - so unfortunately your project doesn't qualify.
